name: Cloud Foundry Auto Start

on:
  schedule:
    - cron: '20 0 * * *'  # 北京时间8:20执行
  workflow_dispatch:       # 允许手动触发

jobs:
  start-cf-apps:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: 1. 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: 2. 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: ''  # 禁用自动缓存，避免旧依赖干扰

    - name: 3. 创建并激活虚拟环境
      run: |
        python -m venv .venv
        source .venv/bin/activate
        echo "当前Python路径：$(which python)"
        echo "虚拟环境激活成功"

    - name: 4. 安装依赖并验证
      run: |
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # 仅验证核心依赖（不验证 telegram.utils）
        echo "=== 已安装的依赖 ==="
        pip list | grep -E "telegram|requests"
        # 验证 telegram 模块是否能正常导入
        echo "=== 验证telegram模块 ==="
        python -c "import telegram; print('telegram版本：', telegram.__version__)"
        python -c "from telegram import Bot; print('Bot类导入成功')"
        python -c "from telegram.constants import ParseMode; print('ParseMode导入成功')"

    - name: 5. 运行CF自动启动脚本
      run: |
        source .venv/bin/activate
        python cf_auto_start.py
