name: Cloud Foundry Auto Start

on:
  schedule:
    - cron: '0 8 * * *'  # 每天UTC时间8点运行（北京时间16点）
  workflow_dispatch:       # 允许手动触发

jobs:
  start-cf-apps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install requests

    - name: Run Cloud Foundry Auto Start
      run: python cf_auto_start.py
      env:
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        CF_API_ENDPOINT: ${{ secrets.CF_API_ENDPOINT }}
        CF_ORG: ${{ secrets.CF_ORG }}
        CF_APPS: ${{ secrets.CF_APPS }}
