name: SAP BTP Auto Start

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '30 0 * * *'  # 每天 UTC 时间 00:30（北京时间 08:30）

jobs:
  start-apps:
    name: Start SAP BTP Applications
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 设置超时时间

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run CF Auto Start Script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        CF_USERNAME_1: ${{ secrets.CF_USERNAME_1 }}
        CF_PASSWORD_1: ${{ secrets.CF_PASSWORD_1 }}
        CF_ORG_1: ${{ secrets.CF_ORG_1 }}
        CF_APPS_1: ${{ secrets.CF_APPS_1 }}
        CF_USERNAME_2: ${{ secrets.CF_USERNAME_2 }}
        CF_PASSWORD_2: ${{ secrets.CF_PASSWORD_2 }}
        CF_ORG_2: ${{ secrets.CF_ORG_2 }}
        CF_APPS_2: ${{ secrets.CF_APPS_2 }}
      run: |
        python cf-autostart.py

    - name: Send success notification
      if: success()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          -d chat_id="$TELEGRAM_CHAT_ID" \
          -d text="✅ <b>SAP BTP 启动成功！</b>%0A%0A⏰ 时间: $(date '+%Y-%m-%d %H:%M:%S')%0A📊 状态: 所有应用启动完成%0A%0A<code>下次执行: 明天 08:30</code>" \
          -d parse_mode="HTML" \
          -d disable_web_page_preview="true"

    - name: Send failure notification
      if: failure()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          -d chat_id="$TELEGRAM_CHAT_ID" \
          -d text="❌ <b>SAP BTP 启动失败</b>%0A%0A📦 工作流: $GITHUB_WORKFLOW%0A🏷️ 运行ID: $GITHUB_RUN_ID%0A⏰ 时间: $(date '+%Y-%m-%d %H:%M:%S')%0A%0A🔍 查看 " \
          -d parse_mode="HTML" \
          -d disable_web_page_preview="true"
