name: Cloud Foundry Auto Start

on:
  schedule:
    - cron: '20 0 * * *'  # 每天UTC时间0:20（北京时间8:20）执行
  workflow_dispatch:       # 允许手动触发工作流

jobs:
  start-cf-apps:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # 防止工作流无限运行

    steps:
    - name: 检出代码
      uses: actions/checkout@v4  # 拉取当前仓库代码

    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # 与脚本兼容的Python版本
        cache: 'pip'  # 缓存依赖以加速后续运行

    - name: 创建并激活虚拟环境
      run: |
        python -m venv .venv
        echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
        echo "$PWD/.venv/bin" >> $GITHUB_PATH  # 将虚拟环境加入PATH，无需每次source

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        # 安装指定版本的依赖以确保兼容性
        pip install "python-telegram-bot==20.7"
        pip install requests

    - name: 验证依赖安装
      run: |
        python --version
        pip list | grep -E "telegram|requests"  # 确认关键依赖已安装

    - name: 运行Cloud Foundry自动启动脚本
      env:
        # Cloud Foundry账号1配置
        CF_USERNAME_1: ${{ secrets.CF_USERNAME_1 }}
        CF_PASSWORD_1: ${{ secrets.CF_PASSWORD_1 }}
        CF_ORG_1: ${{ secrets.CF_ORG_1 }}
        CF_SPACE_1: ${{ secrets.CF_SPACE_1 || 'dev' }}  # 默认为dev空间
        CF_APPS_1: ${{ secrets.CF_APPS_1 }}  # 应用列表，用逗号分隔
        
        # Cloud Foundry账号2配置
        CF_USERNAME_2: ${{ secrets.CF_USERNAME_2 }}
        CF_PASSWORD_2: ${{ secrets.CF_PASSWORD_2 }}
        CF_ORG_2: ${{ secrets.CF_ORG_2 }}
        CF_SPACE_2: ${{ secrets.CF_SPACE_2 || 'dev' }}
        CF_APPS_2: ${{ secrets.CF_APPS_2 }}
        
        # Telegram通知配置
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        
        # 日志级别（可选，默认INFO）
        LOG_LEVEL: INFO
      run: |
        python cf_auto_start.py  # 执行主脚本

    - name: 失败时上传日志
      if: failure()  # 仅在工作流失败时执行
      uses: actions/upload-artifact@v4
      with:
        name: cf-auto-start-logs
        path: cf_auto_start.log  # 上传脚本生成的日志文件
        retention-days: 7  # 日志保留7天，便于排查问题
