name: CF App Start
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu - latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup - python@v3
        with:
          python - version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python - telegram - bot
      - name: Run the script
        env:
          CF_USERNAME_1: ${{ secrets.CF_USERNAME_1 }}
          CF_PASSWORD_1: ${{ secrets.CF_PASSWORD_1 }}
          CF_API_ENDPOINT_1: ${{ secrets.CF_API_ENDPOINT_1 }}
          CF_ORG_1: ${{ secrets.CF_ORG_1 }}
          CF_SPACE_1: ${{ secrets.CF_SPACE_1 }}
          CF_APPS_1: ${{ secrets.CF_APPS_1 }}
          CF_USERNAME_2: ${{ secrets.CF_USERNAME_2 }}
          CF_PASSWORD_2: ${{ secrets.CF_PASSWORD_2 }}
          CF_API_ENDPOINT_2: ${{ secrets.CF_API_ENDPOINT_2 }}
          CF_ORG_2: ${{ secrets.CF_ORG_2 }}
          CF_SPACE_2: ${{ secrets.CF_SPACE_2 }}
          CF_APPS_2: ${{ secrets.CF_APPS_2 }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python cf_auto_start.py
