name: Cloud Foundry Auto Start
on:
  schedule:
    - cron: '30 10 * * *'  # 新加坡时间8:30（UTC时间0:30）
  workflow_dispatch:       # 允许手动触发
jobs:
  .github/workflows/sap-btp-auto-start.yml:
    runs-on: ubuntu - latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup - python@v4
        with:
          python - version: '3.9'
      - name: Install dependencies
        run: |
          pip install requests python - telegram - bot
      - name: Debug environment variables
        run: |
          echo "CF_USERNAME_1: ${{ secrets.CF_USERNAME_1 && '已设置' || '未设置' }}"
          echo "CF_PASSWORD_1: ${{ secrets.CF_PASSWORD_1 && '已设置' || '未设置' }}"
          echo "CF_API_ENDPOINT_1: ${{ secrets.CF_API_ENDPOINT_1 && '已设置' || '未设置' }}"
          echo "CF_ORG_1: ${{ secrets.CF_ORG_1 && '已设置' || '未设置' }}"
          echo "CF_APPS_1: ${{ secrets.CF_APPS_1 && '已设置' || '未设置' }}"
          echo "CF_USERNAME_2: ${{ secrets.CF_USERNAME_2 && '已设置' || '未设置' }}"
          echo "CF_PASSWORD_2: ${{ secrets.CF_PASSWORD_2 && '已设置' || '未设置' }}"
          echo "CF_API_ENDPOINT_2: ${{ secrets.CF_API_ENDPOINT_2 && '已设置' || '未设置' }}"
          echo "CF_ORG_2: ${{ secrets.CF_ORG_2 && '已设置' || '未设置' }}"
          echo "CF_APPS_2: ${{ secrets.CF_APPS_2 && '已设置' || '未设置' }}"
          echo "TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN && '已设置' || '未设置' }}"
          echo "TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID && '已设置' || '未设置' }}"
      - name: Run Cloud Foundry Auto Start
        run: python cf_auto_start.py
        env:
          CF_USERNAME_1: ${{ secrets.CF_USERNAME_1 }}
          CF_PASSWORD_1: ${{ secrets.CF_PASSWORD_1 }}
          CF_API_ENDPOINT_1: ${{ secrets.CF_API_ENDPOINT_1 }}
          CF_ORG_1: ${{ secrets.CF_ORG_1 }}
          CF_APPS_1: ${{ secrets.CF_APPS_1 }}
          CF_USERNAME_2: ${{ secrets.CF_USERNAME_2 }}
          CF_PASSWORD_2: ${{ secrets.CF_PASSWORD_2 }}
          CF_API_ENDPOINT_2: ${{ secrets.CF_API_ENDPOINT_2 }}
          CF_ORG_2: ${{ secrets.CF_ORG_2 }}
          CF_APPS_2: ${{ secrets.CF_APPS_2 }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
